name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Django image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: GiftcardSite/Dockerfile
        push: true
        tags: nyuappsec/assign3:v0

    - name: Build and push Proxy image
      uses: docker/build-push-action@v5
      with:
        context: ./proxy
        file: ./proxy/Dockerfile
        push: true
        tags: nyuappsec/assign3-proxy:v0

    - name: Build and push MySQL DB image
      uses: docker/build-push-action@v5
      with:
        context: ./db
        file: ./db/Dockerfile
        push: true
        tags: nyuappsec/assign3-db:v0

